import numpy as np
import matplotlib.pyplot as plt

data = np.loadtxt('data.csv',  skiprows=1, delimiter=',')
print(f'Number of people: {data[:,0].size}')
height = np.array(data[:,1])
weight = np.array(data[:,2])
plt.figure(1)
plt.scatter(height, weight, s=1)
plt.xlabel('Height(cm)')
plt.ylabel('Weight(kg)')
plt.title('Height and weight relationship')
plt.show()
height50 = np.array(data[::50,1])
weight50 = np.array(data[::50,2])
plt.figure(1)
plt.scatter(height50, weight50, s=1)
plt.xlabel('Height(cm)')
plt.ylabel('Weight(kg)')
plt.title('Height and weight relationship of every 50th person')
plt.show()
print(f'Min height: {np.min(height)} cm')
print(f'Max height: {np.max(height)} cm')
print(f'Average height: {np.mean(height)} cm')
    
indMale = (data[:,0]==1)
indFemale = (data[:,0]==0)
heightMale = (data[:,1][indMale])
heightFemale = (data[:,1][indFemale])

print(f'Min male height: {np.min(heightMale)} cm')
print(f'Max male height: {np.max(heightMale)} cm')
print(f'Average male height: {np.mean(heightMale)} cm')

print(f'Min female height: {np.min(heightFemale)} cm')
print(f'Max female height: {np.max(heightFemale)} cm')
print(f'Average female height: {np.mean(heightFemale)} cm')